[build-system]
requires = [
    "wheel",
    "setuptools >= 64",
    "cython >= 3.0.10",
    "numpy >= 1.26.4",
    "cmdstanpy >= 1.2.5"
]
build-backend = "setuptools.build_meta"

[project]
name = "floodstan"
version = "2.2"
authors = [{name = "Julien Lerat, CSIRO Environment", email="julien.lerat@csiro.au"}]
description = "Flood frequency analysis using Stan"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["flood frequency analysis", "flood", "hydrology"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python 3",
    "Programming Language :: Stan",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Hydrology"
]    
requires-python = ">= 3.10"
dependencies = [
    "setuptools",
    "cython >= 3.0.10",
    "numpy>=1.26.4",
    "cmdstanpy>=1.2.5",
    "scipy>=1.13.0",
    "pandas>=2.0.0",
    "matplotlib>=3.10.9",
    "hydrodiy",
]

[dependency-groups]
dev = [
    "statsmodels>=0.14.6",
    "anybadge>=1.16.0",
    "ruff>=0.15.12",
    "pytest>=8.3.5",
    "pytest-allclose>=1.0.0",
    "pytest-cov>=5.0.0"
]


[project.urls]
Homepage = "https://github.com/jlerat/floodstan"
Repository = "https://github.com/jlerat/floodstan"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.pyx", "*.pxd", "*.c", "*.h", "*.stan"]

[tool.uv]
no-build-isolation-package = ["floodstan"]
default-groups = []

[tool.uv.sources]
hydrodiy = { git = "https://github.com/csiro-hydroinformatics/hydrodiy" }
