name: Cook tests

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: self-hosted
    
    strategy:
      max-parallel: 5
    
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
     
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Create conda environment if needed
        run: |
           source $CONDA/etc/profile.d/conda.sh || true
           conda env create -f env_floodstan.yml || true

      - name : Install hydrodiy package in conda env 
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          echo "Conda env: "
          conda info --envs | grep '*' | sed 's/.*\* //g'

          cd $GITHUB_WORKSPACE
          mkdir -p src
          cd src
          git clone https://github.com/csiro-hydroinformatics/hydrodiy.git
          cd hydrodiy
          
          echo "--- hydrodiy install : located in $PWD ---"
          # .. create a tmp directory for pip install
          mkdir -p tmp
          export TMPDIR=tmp

          python -m pip uninstall -y hydrodiy || true
          python -m pip install -e .

      - name : Install floodstan package in conda env 
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          echo "Conda env: "
          conda info --envs | grep '*' | sed 's/.*\* //g'

          cd $GITHUB_WORKSPACE
          echo "--- floodstan install : located in $PWD ---"
          # .. create a tmp directory for pip install
          mkdir -p tmp
          export TMPDIR=tmp
          
          python -m pip uninstall -y floodstan || true
          python -m pip install -e .

      - name: Run sampling tests
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          echo "Conda env: "
          conda info --envs | grep '*' | sed 's/.*\* //g'

          cd $GITHUB_WORKSPACE
          echo "--- floodstan sampling test : located in $PWD ---"
          ./tests/sample_univariate_cook.sh 
 
      - name: Upload sampling test results
        uses: actions/upload-artifact@v4
        with:
          name: sample-univariate-cook
          path: tests/images/sampling/univariate_cook/*.*


