name: Build floodstan

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 5
    
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
     
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Create conda environment if needed
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda env create -f env_floodstan.yml

      - name : Install hydrodiy package in conda env 
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          cd $GITHUB_WORKSPACE
          mkdir -p src
          cd src
          git clone https://github.com/csiro-hydroinformatics/hydrodiy.git
          cd hydrodiy
          echo "--- hydrodiy install : located in $PWD ---"
          pip install -e .

      - name : Install floodstan package in conda env 
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          cd $GITHUB_WORKSPACE
          echo "--- floodstan install : located in $PWD ---"
          pip install -e .

      - name: Lint with flake8
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          cd $GITHUB_WORKSPACE
          flake8 src/floodstan

      - name: Run tests
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate env_floodstan
          cd $GITHUB_WORKSPACE
          echo "--- floodstan test : located in $PWD ---"
          pytest --ignore=src/hydrodiy --cov=floodstan --cov-report=xml --cov-report=html --cov-report=term-missing tests
      
      - name: Upload pytest test log files
        uses: actions/upload-artifact@v3
        with:
          name: pytest-logs
          path: tests/*.log
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-coverage
          path: htmlcov/*.*

      - name: Parse coverage report
        run: |
          python -c "import xml.etree.ElementTree as ET; coverage = float(ET.parse('coverage.xml').getroot().get('line-rate')) * 100; print(f'{round(coverage)}%')" > coverage.txt

      - name: Update gist
        run: |
          echo "{\"files\": {\"coverage.json\": {\"content\": \"$(cat coverage.txt)\"}}}" > coverage.json
          curl -X PATCH -H "Authorization: token ${{ secrets.COVERAGE_GIST_TOKEN }}" \
                -d @coverage.json \
                "https://api.github.com/gists/${{ secrets.COVERAGE_GIST_ID }}"


